/// Flutter icons Costom
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Costom
///      fonts:
///       - asset: fonts/Costom.ttf
///
/// 
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
///
import 'package:flutter/widgets.dart';

class Costom {
  Costom._();

  static const _kFontFam = 'Costom';
  static const String? _kFontPkg = null;

  static const IconData wanted = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData my = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
